include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_return: error
    must_be_immutable: error
    avoid_void_async: ignore
    sort_pub_dependencies: ignore
    overridden_fields: ignore
    annotate_overrides: ignore